### ISSUE TITLE
No way to access the current element?

### ISSUE THREAD

**Issue by scratchoo** [mdbassit/Coloris#103]
Hi, first of all thank you for this cool lib, however I find it strange to not able to access the current input on the onChange function, how you can get the input that the color changed for?

**Comment by mdbassit** [comment]
Your condescending way of phrasing this aside, thank you for reporting this! 
It wasn't implemented simply because I don't need it, and seeing how this is a tool I created for my own use, there is nothing strange about not adding something I don't need.

Anyway, I will add that soon as it does make sense.

**Comment by melloware** [comment]
0.20.0 has been published to NPM with this fix
