### ISSUE TITLE
Per instance configuration

### ISSUE THREAD

**Issue by jepsar** [mdbassit/Coloris#28]
Not sure if this is a question or a feature request. Currently it seems that configuration can only be done globally. Is it possible to have different instances with a different configuration?

**Comment by mdbassit** [comment]
Coloris is designed to have only one instance per page, it is not possible to have different configurations per instance.

**Comment by jepsar** [comment]
With multiple inline instances (#25) I think somewhat of the same issue will rise.

**Comment by mdbassit** [comment]
In that request, you didn't say anything about multiple inline instances. I said I'd look into adding an option to make the picker always visible and statically positioned, but there can only be one instance of the picker. This is by design and the very reason I decided to make my own picker instead of using an existing one.

I would like to support everyone's use case if possible, but if it conflicts with mine, I'm afraid I'll have to reject it.

**Comment by BNO79** [comment]
I use two different configuration in the same page (one configuration for a modal div and one for the main page), to do that i change at runtime (when show/hide the modal div) the "parent" configuration through the "set" method (Coloris.set({parent: '#multipleEditModal'});)

**Comment by mdbassit** [comment]
@BNO79 Thanks for pointing that out. Indeed, you can change the configuration as many times as you like to simulate multiple instances, but there will only be one real instance of the color picker.
