### ISSUE TITLE
More detailed instructions on how to use the color picker?

### ISSUE THREAD

**Issue by NeekoVN** [mdbassit/Coloris#36]
Maybe you can clarify more about where's the output value, and stuffs like that. It took me quite a while to find out everything i need to know in order to use it properly.
Btw i don't know why but my themeMode isn't working, i changed themeMode to dark but it doesn't do anything.

**Comment by mdbassit** [comment]
Thanks for your feedback! Could you please specify what exactly you had difficulties accomplishing with the color picker? What do you mean when you say "where's the output value"?

Setting the `themeMode` to dark works as intended for me. Could you share your code so I can take a look at it?

**Comment by NeekoVN** [comment]
Hi. Is using value of the input is the right way of using the color picker or there's something else that I haven't found out yet. 
I think I'm supposed to configure it in CSS maybe?
Here is a screenshot of me changing themeMode to dark but nothing happened.
![Screenshot_2022-03-22_22-50-06](https://user-images.githubusercontent.com/76953348/159523234-2ef75d94-6b0a-4fd3-8487-4e28cefba63d.png)

**Comment by NeekoVN** [comment]
By the way, the color picker's input fiels doesn't take `hsl(H, S%, L%)` value

**Comment by mdbassit** [comment]
It looks like it wasn't obvious from the documentation that you need to call `Coloris()` and pass an options object to it in order to configure the color picker. You shouldn't modify the JavaScript source at all to use or customize the picker.

To activate **dark** mode and set the format to **hsl** you need to add this code at the bottom of your page:

```html
<script>
  Coloris({
    themeMode: 'light',
    format: 'hsl'
  });
</script>
```

I hope that helps.
