### ISSUE TITLE
Non-passive event listener [Google Chrome]

### ISSUE THREAD

**Issue by gmunumel** [mdbassit/Coloris#37]
Hello guys,

Thanks for the library.

I just started using the library and as soon I opened in Google Chrome I got this warning message:

```
coloris.js:928 [Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
```

Any idea to remove the warning?

**Comment by mdbassit** [comment]
Hello and thank for your feedback!
Actually that is the intended behavior. The `touchstart` event in this case needs to block the scrolling, as it's used to move the marker inside the color spectrum. If scroll is enabled, the page will scroll instead of updating the selected color in the picker.
I hope this answers your question.

**Comment by gmunumel** [comment]
Yes, it does. I guess there is not way to prevent the warning message?!

But, at least, now that I know the detail I can live with it. ;)

Thanks.

**Comment by mdbassit** [comment]
That warning message is right about 95% of the time (completely made up that number), but this time it is not.
Unfortunately, there is no way to prevent the warning.
