### ISSUE TITLE
Not Working with ajax generated content

### ISSUE THREAD

**Issue by Aks8578** [mdbassit/Coloris#49]
When the ajax content is loaded it should callback the coloris.js. then it will work fine in ajax generated content.

**Comment by melloware** [comment]
Can you please provide and example or reproducer of your problem?  I don't understand your issue.

**Comment by savissimo** [comment]
I think @Aks8578 means that, if you edit the DOM, the newly-inserted elements with the `data-coloris` attribute are not transformed by Coloris. 

To solve the problem, one cannot rely on Coloris's autostart feature, because it only affects element that are already present at page load. You must explicitly call the `Coloris()` function with the desired parameters every time new content is available. I would suggest making a function for that:

```javascript
function updateColoris() {
  Coloris({
    // desired configuration
  })
}
```

Then you would do something like:

```javascript
jQuery.ajax('https://url', {
  success: () => { updateColoris() }
})
```
